//crtest2 environment changes
//let adminhost = "https://crtest2.convertrite.com/api/convertriteadmin/";
//let corehost = "https://crtest2.convertrite.com:886/api/convertritecore/";
//let cloudConnector = "https://crtest2.convertrite.com:199/";

//cr20 environment changes
let adminhost = "https://cr20.convertrite.com/api/convertriteadmin/";
let corehost = "https://cr20.convertrite.com:886/api/convertritecore/";
let cloudConnector = "https://cr20.convertrite.com:199/";

//local environment changes
//let adminhost = "http://localhost:8080/api/convertriteadmin/";
//let corehost = "http://localhost:9000/api/convertritecore/";
//let cloudConnector = "http://localhost:7000/";

var riteUTils = {
  riteProps: {
    getClients: adminhost + "clients",
    getClientdetails: adminhost + "auth/",
    loginUser: adminhost + "auth/signin",
    getProjectsAndObjects: adminhost + "getProjectsAndObjects",
    getImportProjectsAndObjects: corehost + "getProjectsAndObjects",
    getAllMappingSets: corehost + "getAllMappingSets",
    getAllProjectHeaders: corehost + "getallprojectheaders",
    getProjectLines: corehost + "insertProjectActivities",
    getlovbylookupsetname: corehost + "getlovbylookupsetname",
    upsertprojectactivities: corehost + "upsertprojectactivities",
    getprojectlinesbyid: corehost + "getprojectlinesbyid",
    saveprojectheaders: corehost + "saveprojectheaders",
    getMappingValuesBySetId: corehost + "getMappingValuesBySetId/",
    SaveMappingSetHeader: corehost + "SaveMappingSetHeader",
    saveallmappingvalues: corehost + "saveallmappingvalues/",
    getAllFormulaSets: corehost + "getAllFormulaSets",
    getFormulaVaaluesSetById: corehost + "getFormulaSetById/",
    saveFormulaSetHeader: corehost + "saveFormulaSet",
    saveFormulaSetLines: corehost + "saveFormulaSet/",
    deleteFormulaSets: corehost + "deleteFormulaSet/",
    getAllLookUpSets: corehost + "getAllLookUpSets",
    saveLookUpSet: corehost + "saveLookUpSet",
    getLookUpValuesBySetId: corehost + "getLookUpValuesBySetId/",
    saveallLookUpvalues: corehost + "saveallLookUpvalues/",
    getParentObjectsByProjectId: corehost + "getParentObjectsByProjectId",
    getObjectsByObjectCode: corehost + "getObjectsByObjectCode",
    getobjects: adminhost + "objects/",
    // uploadFiles : "https://cr20testtest.convertrite.com:886/uploadfile",

    uploadFiles: corehost + "metadata/uploadfile",
    downloadsourcetemplate: corehost + "metadata/downloadsourcetemplate",
    getsourcetemplates: corehost + "source/getsourcetemplates",
    getsourcetemplatecolumns: corehost + "source/getsourcetemplatecolumns",
    savesourcetemplateheaders: corehost + "source/savesourcetemplateheaders",
    savesourcetemplatecolumns: corehost + "source/savesourcetemplatecolumns",
    getsourcetablenames: corehost + "source/getsourcetablenames",
    loadSourceTemplateMetaData: corehost + "source/loadSourceTemplateMetaData",
    createstgtable: corehost + "source/createstgtable",
    loadSourceData: corehost + "source/loadSourceData",
    updateSourceTemplateColumns: corehost + "source/updateSourceTemplateColumns",
    getsourcecolumnsbyname: corehost + "source/getsourcecolumnsbyname",
    getVersionData: "js/data/version.json",
    getallcloudtemplates: corehost + "cloud/" + "getallcloudtemplates",
    getcloudtemplatecolumns: corehost + "cloud/" + "getcloudtemplatecolumns",
    getallcloudtemplates: corehost + "cloud/" + "getallcloudtemplates",
    getallclouddatarequest:
      cloudConnector + "cloudconnector/getclouddatabypodid",
    getallstatus: cloudConnector + "cloudconnector/getallstatus",
    dataprocessing: cloudConnector + "cloudconnector/dataprocessing",
    deleteadhocdata: cloudConnector + "cloudconnector/deleteadhocdata/",
    getcloudtemplatecolumns: corehost + "cloud/" + "getcloudtemplatecolumns",
    getdummy: "js/data/cld.json",
    getcloudsourcecolumns: corehost + "cloud/" + "getcloudsourcecolumns",
    savecloudtemplateheaders: corehost + "cloud/" + "savecloudtemplateheaders",
    saveallcloudtemplatecolumns:
      corehost + "cloud/" + "saveallcloudtemplatecolumns",
    getCloudTablesTemplates: corehost + "cloud/" + "getcloudtablestemplates",
    getAllUserHooks: corehost + "getAllUserHooks",
    saveUserHook: corehost + "saveUserHook",
    delteUserHookById: corehost + "delteUserHookById/",
    getfbditemplates: corehost + "fbdi/getAllfbditemplates",
    getfbditempcols: corehost + "fbdi/getfbditempcols",
    savefbditemphdrs: corehost + "fbdi/savefbditemphdrs",
    savefbditempcols: corehost + "fbdi/savefbditempcols",
    getfbdicolsequence: corehost + "fbdi/getfbdicolsequence",
    podcloudconfigs: adminhost + "podcloudconfigs",
    getObjectsByUserId: adminhost + "getObjectsByUserId",
    getTemplateHooks: corehost + "getTemplateHooks/",
    saveTemplateHooks: corehost + "saveTemplateHooks/",
    loadmetadatafromcloud: corehost + "metadata/loadmetadatafromcloud",
    getTemplateHooks: corehost + "cloud/" + "getTemplateHooks/",
    saveTemplateHooks: corehost + "cloud/" + "saveTemplateHooks/",
    transformDataToCloud: corehost + "conversion/transformDataToCloud",
    downloadfbdi: corehost + "conversion/downloadfbdi",
    generatehdl: corehost + "conversion/generatehdl",
    gettemplatestate: corehost + "conversion/gettemplatestate",
    getprocessrequests: corehost + "conversion/getprocessrequests",
    getAllObjectGroupHdrsView: corehost + "getAllObjectGroupHdrsView",
    getAllLinesInObjectGroup: corehost + "getAllLinesInObjectGroup/",
    saveObjectGroupHdr: corehost + "saveObjectGroupHdr",
    saveObjectGroupLines: corehost + "saveObjectGroupLines/",
    generatesequence: corehost + "metadata/generatesequence",
    gettemplatestatistics: corehost + "dashboard/gettemplatestatistics",
    loadandimportdatav1: corehost + "conversion/loadandimportdatav1",
    getCrTransformStats: corehost + "dashboard/getCrTransformStats",
    downloadCloudImportRejRec: corehost + "reconcile/downloadCloudImportRejRec",
    downloadCloudImportSuccessRec:
      corehost + "reconcile/downloadCloudImportSuccessRec",
    downloadValFailRec: corehost + "reconcile/downloadValFailRec",
    uploadfiletoftp: corehost + "metadata/uploadfiletoftp",
    loadSourceDataToExternalTable: corehost + "source/loadSourceDataToExternalTable",
    loadLookUpfromfile: corehost + "loadLookUpfromfile",
    loadmappingvalues: corehost + "loadmappingvalues",
    getAllBatchNames: corehost + "crdata/getbatchnames",
    hdlCloudMetaData: corehost + "metadata/loadhdlcloudmetadata",
    userswithemail: adminhost + "userswithemail",
    savegetobjectinformation: adminhost + "objects",
  },
  riteLbl: {
    podName: "POD Name",
    parentObject: "Parent Object Name",
    objectCode: "Object Name",
    projectName: "Project Name",
    loadData: "Load Data",
    loadImport: "Load Import",
    metaDataTableName: "MetaData Table Name",
    cloudRefTableName: "Cloud MetaData Table",
    sourceTemplate: "Source Template",
    version: "Version",
    cloudTempWb: "Cloud Template WorkBench",
    srcTempWb: "Source Template WorkBench",
    conversionWb: "Conversion WorkBench",
    manageProjects: "Manage Your Projects",
    objGroup: "Object Grouping",
    tempGroup: "Template Grouping",
    dateConfig: "Date Configuration",
    mappingName: "Mapping Name",
    validationType: "Validation Type",
    mappingType: "Mapping Type",
    mappingCode: "Mapping Code",
    defineMaping: "Define Mapping Set",
    formulaSet: "Formual Set",
    cludAccConfig: "Cloud Access Configuration",
    cludConfig: "Cloud Configuration",
    reconConfig: "Reconciliation Configuration",
    extSrcConfig: "External Source Configuration",
    fbdiCtrl: "FBDI WorkBench-Ctrl",
    fbdiXlsm: "FBDI WorkBench-XLSM",
    lookupWb: "Lookup WorkBench",
    cludAdhoc: "Cloud Sql Adhoc Query",
    loadMetaData: "Load MetaData",
    loadImptMData: "Load Import MetaData",
    stusOfJob: "Status of Jobs",
    templateName: "Template Name",
    templateCode: "Template Code",
    code: "Code",
    stagingTableName: "Staging Table Name",
    viewName: "View Name",
    email: "Email",
    password: "Password",
    description: "Description",
    projectManager: "Project Manager",
    startDate: "Start Date",
    endDate: "End Date",
    destinationType: "Destination Type",
    tableName: "Table Name",
    metadata: "Metadata",
    sqlQuery: "Sql Query",
    formulaSetName: "Formula Name",
    formulaSetCode: "Formula Code",
    formulaType: "Formula Type",
    formulaText: "Formula Text",
    noofParams: "No. of Params",
    lookupName: "Lookup Name",
    lookupCode: "Lookup Code",
    relatedTo: "Related To",
    batchName: "Batch Name",
    batchSize: "Batch Size",
    columnName: "Column Name(V)",
    columnType: "Column Type",
    opttype: "Operation Type",
    sequence: "Sequence",
    fbdiControl: "FBDI Control",
    version: "Version",
    hookName: "Hook Name",
    hookCode: "Hook Code",
    hookType: "Hook Type",
    hookText: "Hook Text",
    preTransfomHook: "Pre Transform Hook",
    PostTransformHook: "Post Transform Hook",
    FBDIHDLgenerationHook: "FBDI HDL Generation Hook",
    selecttemp: "Select Template",
    groupName: "Group Name",
    groupCode: "Group Code",
    ctrlFile: "Control File Name",
    reqForFbdi: "Requied for FBDI Cloud Meta Data",
    width: "Width",
    cldTemplate: "Cloud Template",
    parameters: "Parameter List",
  },
  riteHeader: {
    headers: {
      role: sessionStorage.getItem("user_role"),
      roleid: sessionStorage.getItem("roleid"),
      authorization: sessionStorage.getItem("id_token"),
      "Content-Type": "application/json",
    },
  },
  positions: {
    my: { vertical: "top", horizontal: "end" },
    at: { vertical: "top", horizontal: "end" },
    of: "window",
  },
};
