props = {
	getcloudtemplates: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getallcloudtemplates',
	getpods: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getpods',
	getprojectname: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getprojectsbypod',
	getAllprojectnamesURL: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getprojects',
	getimportdialoguetable: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getcloudtemplatecolumns',
	getsrccolsURL: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getcloudsourcecolumns',
	createTableURL: ' https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/createcloudstgtable',
	createbaselineURL: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/createdynamicview',
	savetempHeaderURL: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/savecloudtemplateheaders',
	savetempLinesURL: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/savecloudtemplatecolumns',
	mappingSetNameLOVURL: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getcloudmappingsetnames',
	getparentobjcodeURL: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getlovvalues?lovValues=PARENTOBJECTCODE',
	getbuURL: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getlovvalues?lovValues=BU&podId=1001&projectId=1',
	getobjcodeURL: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getlovvalues?lovValues=OBJECTCODE&podId=1001&projectId=1',
	getcloudsourcetablenameUrl: 'https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getCloudTablesTemplates',
	getsourcetemplates: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/getsourcetemplates",
	createstgtable: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/createstgtable",
	createdynamicview: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/createdynamicview",
	getsourcecolumns: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/getsourcetemplatecolumns",
	savesourcetemplateheaders: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/savesourcetemplateheaders",
	savesourcetemplatecolumns: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/savesourcetemplatecolumns",
	getsourcetemplates: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/getsourcetemplates",
	getsourcecolumnsbyTable: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/getsourcecolumnsbyname",
	getSourceTablesURL: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/getsourcetablenames",
	getallsourceobjects: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/getallsourceobjects",
	getCloudcolumns: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/getcloudcolumns",
	getMappingSourceColumns: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/getsourcecolumns",
	getSRCFieldsURL: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/getsourcefields",
	getCloudValuesURL :"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/getcloudvalues",
	getAllMappingSets: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/getallcloudmappingsets",
	saveMappingHeaders:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/savecloudmappingsetheaders",
	saveMappingLines:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/savecloudmappingsetcolumns",
	getCloudMappingSetValues : "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/getcloudmappingsetvalues",
	downloadcloudtemplateURL : "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/downloadcloudtemplate",
	downloadsourcetemplateURL : "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/downloadsourcetemplate",
	createcloudrecordURL: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/processcloudmetadatarec",
	createsourcerecordmetaURL: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/processsourcemetadatarec",
	createsourcerecURL : "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/processsourcestagingdata",
	savelookupheaderURL: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/LookUp/savecloudlookupsetheaders",
	savelookupsetvalueURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/LookUp/savecloudlookupsetvalues",
	getcloudlookupURL: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/LookUp/getlookupsetheaders",
	getcloudlookuptableURL : "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/LookUp/getlookupsetvalues",
	uploadtempURL: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/uploadfile",
	getconversiontabledata:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getprocessrequests",
	getconversiontempname: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/gettemplatestate",
	downloadeFBDItemp:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/generatefbdi",
	conversionbtnsdata : "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/processjob",
	getprojentrylov:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getprojectentrylovs",
	getallprojheader:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getallprojectheaders",
	getprojtemplines:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getprojectlinesbyid",
	getgriddata: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getrecordspostjobexecution",
	loadewbsURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/loadwbs",
	saveloaddataheaderURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/saveprojectheaders",
	loadtaskURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/loadtask",
	loadmetadatloadbtn:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/processsourcestagingdata",
	saveloadwbsdataURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/updateprojectwbsselections",
	saveactivitylinesURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/upsertprojectactivities",
	getcloudlookupcolumnnameURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/LookUp/getcolumnnames",
	gettasktypeURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getprojectentrylovs",
	getprereqURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getprerequisitetask",
	getlookupsetURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/LookUp/getlookupset",
	getLookUpValuesURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/LookUp/getlookupvalues",
	savelookupheaderURL: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/LookUp/savelookupsetheaders",
	savelookupvaluesURL: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/LookUp/savelookupvalues",
	getrelatedtolovURL: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getrelatedtolov?lovValue=Related To",
	getactaulvalURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getactualvaluelov",
	getcommonLOVURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getcommonlov",
	getpodsnewURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getpods",
	getbunewURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getbulov",
	getpodprojscrURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getlovbylookupsetname?lookupSetName=pod",
	getprojinproscrURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getlovbylookupsetname?lookupSetName=project",
	getlovfromlukupURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getlovbylookupsetname",
	getcloudclofrmlURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getcloudcolumns",
	// getsrccolfrmlURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getsourcetablenames",
	// New requirement by damodhar on 23-11-2020
	getsrccolfrmlURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getallsourceobjects",
	getformulasets:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getformulasets",
	saveformulaheader:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/saveformulasetheader",
	getformulalines:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getformulasettables",
	getformulacolumns:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getformulacolumns",
	getsrccollovdataURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getsourcecolumns",
	saveformulatable:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/saveformulasettables",
	saveformulacolumnsURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/saveformulacolumns",
	getparobjcodeurl: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getlovbylookupsetname?lookupSetName=parent object code",
	getobjcodedataURL: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getobjectcodes",
	getsrccloudtempURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getcloudsourcecolumnsbyids",
	gettemplatestatistics:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/gettemplatestatistics",
	gettaskbreakdown: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/gettaskbreakdown",
	copysourcetemplate:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/copysourcetemplate",
	copycloudtemplate:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/copycloudtemplate",
	copymappingset:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/copymappingset",
	copyformulaset:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/copyformulaset",
	testsqldata:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/testsqldata",
	testsqlsyntax:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/testsqlsyntax",
	postclouddataprocessingrequest:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/clouddataprocessingrequest",
	Getallstagedataloadstatus:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getallstagedataloadstatus",
	exportfailedsrcrecrds:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/exportfailedrecordsascsv",
	getallclouddataRequestURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getallclouddatarequest",	
	saveCloudDataProcessRequestURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/clouddataprocessingrequest",	
	getProcessJobRequestURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getprocessjobs",	
	getformulaSetTableURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getallsourceobjects",	
	getformulaSetColumnsURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getsourcecolumnsbyview",	
	getfbditemplatename:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getfbditemplatename",	
	getsheetname: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getsheetname",	
	saveFbdiTemplateHeaderURL:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/savefbditemplateheader",	
	getfbdicolumnsequence:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getfbdicolumnsequence",
	getsourcetemplatestatistics:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getsourcetemplatestatistics",
	getfbditemplates:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getfbditemplates",
	getfbditemplatecolumns:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getfbditemplatecolumns",
	downloadcsvfile:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/downloadcsvfile",
	savefbditemplatecolumns:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/savefbditemplatecolumns",
	generatesequence:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/generatesequence",
	exportfailedrecords:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/exportfailedrecords",
	geterpintegrationmetadata:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/geterpintegrationmetadata",
	geterpintegrationmetadatabyids:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/geterpintegrationmetadatabyids",
	saveerpintegrationmetadata:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/saveerpintegrationmetadata",
	geterpintegrationdetails:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/geterpintegrationdetails",
	getjobstatus:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getjobstatus",
	loadandimportdata:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/loadandimportdata",
	downloadexportoutput:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/downloadexportoutput",
	getebsintegrationdetails:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getebsintegrationdetails",
	saveebsintegrationdetails:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/saveebsintegrationdetails",
	getdblink:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getdblink",
	loaddatafromebs:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/loaddatafromebs",
	loadmetadatafromebs:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/loadmetadatafromebs",
	getlookupsetname:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/LookUp/getlookupsetname",
	searchbyoperator:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/LookUp/searchbyoperator",
	processreconcile:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/processreconcile",
	processreconcilereport:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/processreconcilereport",
	getobjectcodegroupings:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getobjectcodegroupings",
	getobjectcodegroupinglines:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getobjectcodegroupinglines",
	saveobjectcodegrouping:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/saveobjectcodegrouping",
	saveobjectcodegroupinglines:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/saveobjectcodegroupinglines",
	gettemplategroupings:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/gettemplategroupings",
	savetemplategrouping:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/savetemplategrouping",
	getdateconfiguration:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getdateconfiguration",
	savedateconfiguration:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/savedateconfiguration",
	loadmetadatafromcloud:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/loadmetadatafromcloud",
	getxlsmtemplates:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getxlsmtemplates",
	savexlsmtemplateheader:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/savexlsmtemplateheader",
	getxlsmtemplatename:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getxlsmtemplatename",
	getsheetnamebyobjectcode:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getsheetnamebyobjectcode",
	savexlsmtemplatecolumns:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/savexlsmtemplatecolumns",
	getxlsmcolumnsequence:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getxlsmcolumnsequence",
	getxlsmtemplatecolumns:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getxlsmtemplatecolumns",
	xlsmgeneratesequence:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/xlsmgeneratesequence",
	uploadsqlfile:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/uploadsqlfile",
	getformulasetsbyobjectid:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getformulasetsbyobjectid",
	getcloudconfig:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getcloudconfig",
	savecloudconfigdetails:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/savecloudconfigdetails",
	copyproject:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/copyproject",
	getallobjectcodes:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getallobjectcodes",
	getcloudobjectrealtedconfig:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getcloudobjectrealtedconfig",
	savecloudobjectrelatedconfig:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/savecloudobjectrelatedconfig",
	gethcmdataloaderdetails:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/gethcmdataloaderdetails",
	getDataSetStatus:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getDataSetStatus",
	hcmloadandimportdata:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/hcmloadandimportdata",
	generatehdl:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/generatehdl",
	processhdlreconcile:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/processhdlreconcile",
	hdlreconcilereport:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/hdlreconcilereport",
	loadhdlcloudmetadata:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/loadhdlcloudmetadata",
	gettransformationreport:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/gettransformationreport",
	updateeditedfailedrec:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/updateeditedfailedrec",
	getusers:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getusers",
	registeruser:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/registeruser",
	userregistrationStatus:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/userregistrationStatus",
	getroles:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getroles",
	saveroles:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/saveroles",
	saveuserroles:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/saveuserroles",
	getuserroles:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getuserroles",
	getroleobjects:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getroleobjects",
	saveroleobject:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/saveroleobject",
	getparentobjectcodebyrole:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getparentobjectcodebyrole",
	getrolesbyusername:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getrolesbyusername",
	getpodsbyrole:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getpodsbyrole",
	getprojectsbyrole:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getprojectsbyrole",
	gettaskownerlov:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/gettaskownerlov",
	gettasks:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/gettasks",
	getchat:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getchat",
	downloadxlsmcolumncsv:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/downloadxlsmcolumncsv",
	savexlsmasblob:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/savexlsmasblob",
	savectlasblob:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/savectlasblob",
	getparentobjectcodes:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getparentobjectcodes",
	searchsrclookups:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/searchsrclookups",
	getsrclookupvalues:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getsrclookupvalues",
	getsrclookupsetnames:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getsrclookupsetnames",
	loadlookupsfromsrc:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/loadlookupsfromsrc",
	getallmappingsetsNew:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/getallmappingsets",
	savecloudmappingsethdr:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/savecloudmappingsethdr",
	savecloudmappingsetvalues:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/savecloudmappingsetvalues",
	getcloudmappingsetvalueNew:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/getcloudmappingsetvalue",
	copycloudmappingset:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/copycloudmappingset",
	deletestagingdata:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/deletestagingdata",
	uploadctlgetcolumnseq:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/uploadctlgetcolumnseq",
	generatexls:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/generatexls",
	loadcustomlookupsfromsrc:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/loadcustomlookupsfromsrc",
	loaddatafromebsv1:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/loaddatafromebsv1",
	processjobv1:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/processjobv1",
	getbatchnames:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getbatchnames",
	loadandimportdatav1:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/loadandimportdatav1",
	// generatefbdiv1:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/generatefbdiv1",
	generatefbdiv1:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/downloadfbdi",
	downloadebsview:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/downloadebsview",
	getsrcsystemlobId:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getsrcsystemlobId",
	saveebsview:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/saveebsview",
	getreconcilestatistics:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getreconcilestatistics",
	loadmappingvalues:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/mappingset/loadmappingvalues",
	getreconciledetails:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getreconciledetails",
	getlookupvaluesbyval:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/LookUp/getlookupvaluesbyval",
	getcldsrctemplateids:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getcldsrctemplateids",
	getprocessrequestsbytype:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getprocessrequestsbytype",
	loadsourcedata:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/loadsourcedata",
	downloadfailedreclogfile:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/downloadfailedreclogfile",
	loadLookUpfromfile:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/cloud/LookUp/loadLookUpfromfile",
	uploadfiletoftp:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/uploadfiletoftp",
	processhdlsummary:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/processhdlsummary",
	hdlsummaryreport:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/hdlsummaryreport",
	saveuserhooks:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/saveuserhooks",
	getuserhooksdtls:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getuserhooksdtls",
	getreconcileerrordetails:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getreconcileerrordetails",
	getdefaultcldsrctemplateids:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getdefaultcldsrctemplateids",
	repopulateorigtransref:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/repopulateorigtransref",
	loadsourcedataatparentobject:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/loadsourcedataatparentobject",
	getreconcileconfig : "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getreconcileconfig",
	savereconcileconfig: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/savereconcileconfig",
	loadrejectnmetadatafrmcld: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/loadrejectnmetadatafrmcld",
	getObjcodeurl: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getlovbylookupsetname?lookupSetName=Object Code",
	getrolesbyemail: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getrolesbyemail",
	userregistrationstatusbyemail: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/userregistrationstatusbyemail",
	getobjectsbyrole: "https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/getobjectsbyrole",
	srctempcolumnsupdate:"https://crtest2.convertrite.com/ConvertRiteSpringBootApiDev/api/source/srctempcolumnsupdate"

}
